### ISSUE TITLE
Comportement pour les 29 février

### ISSUE THREAD

**Issue by bbailleux** [jcfrog/my-life-in-weeks#1]
L'afichage ne se comporte pas comme pour les autres dates quand la date de naissance est le 29/02/×××

Exemple : https://jcfrog.com/mylife/index.html?bdate=29-02-1968&lexp=80

À comparer à : https://jcfrog.com/mylife/index.html?bdate=28-02-1968&lexp=80

**Comment by jcfrog** [comment]
merci, apparemment d'autres aussi ont des problèmes, on va regarder ça

https://jcfrog.com/mylife/index.html?bdate=30-03-1982&lexp=80

**Comment by jcfrog** [comment]
Bug fixed, en tout cas pour ces 2 exemples.
